{
 "title": "Knot.x Server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "InfluxMetrics", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Http Server Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.servers.0.0.0.0:8092.get-requests.mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.servers.$knotxServerAddress.get-requests.mean, 'Mean')"
    },
    {
     "alias": "P 75",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.servers.0.0.0.0:8092.get-requests.p75",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.servers.$knotxServerAddress.get-requests.p75, 'P 75')"
    },
    {
     "alias": "P 99",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.servers.0.0.0.0:8092.get-requests.p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.servers.$knotxServerAddress.get-requests.p99, 'P 99')"
    }
   ]
  },
  {
   "title": "Server endpoints responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "/api/v1/example",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.servers.0.0.0.0:8092.get-requests.api-v1.mean",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.servers.$knotxServerAddress.get-requests.payments.mean, '/content/payment.html')"
    }
   ]
  },
  {
   "title": "Http Server Response Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "2xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.servers.0.0.0.0:8092.responses-2xx.mean_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.servers.$knotxServerAddress.responses-2xx.mean_rate, '2xx')"
    },
    {
     "alias": "4xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.servers.0.0.0.0:8092.responses-4xx.mean_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.servers.$knotxServerAddress.responses-4xx.mean_rate, '4xx')"
    },
    {
     "alias": "5xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.servers.0.0.0.0:8092.responses-5xx.mean_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.servers.$knotxServerAddress.responses-5xx.mean_rate, '5xx')"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.clients.get-requests.m1_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.clients.get-requests.m1_rate, 'out')"
    },
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io.knotx.vertx.http.servers.0.0.0.0:8092.requests.m1_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias($queryPrefix.http.servers.$knotxServerAddress.requests.m1_rate, 'in')"
    }
   ]
  }
 ]
}