datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    user: telegraf
    password: telegraf
    url: http://host.docker.internal:8086
    isDefault: true
  - name: 'Graphite-via-influx'
    type: influxdb
    access: proxy
    database: graphite
    user: grafana
    url: http://host.docker.internal:8086
    jsonData:
      timeInterval: "15s"
    secureJsonData:
      password: grafana