# To execute this docker-swarm yml file use `docker stack deploy -c mocks.yml mocks`

version: '3.7'

networks:
  private:
    driver: overlay

services:
  repository:
    image: nginx:1.16.0
    volumes:
      - "./mocks/content/public_html:/usr/share/nginx/html:ro"
    ports:
      - "4503:80"
    networks:
      - private

  webapi:
    image: nginx:1.16.0
    volumes:
      - "./mocks/webapi:/usr/share/nginx/html"
      - "./mocks/config/webapi-nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "3080:80"
    networks:
      - private