# To execute this docker-swarm yml file use `docker stack deploy -c monitoring.yml monitoring`

version: '3.7'

networks:
  private:
    driver: overlay

volumes:
  influxdb-data:

services:
  influxdb:
    image: influxdb:1.7
    ports:
      - "8086:8086"
      - "2003:2003" # Graphite port
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true # enable Graphite
      - INFLUXDB_DB=cadvisor
    networks:
      - private

  telegraf:
    image: telegraf:1.11
    ports:
      - "8125:8125/udp" # StatsD udp port
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true # enable Graphite
    networks:
      - private

  cadvisor:
    image: google/cadvisor
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - private

  grafana:
    image: grafana/grafana:6.2.5
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config.ini:/etc/grafana/config.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-knotx}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-knotx}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - private
