# To execute this docker-swarm yml file use `docker stack deploy -c target.yml target`

version: '3.7'

networks:
  private:
    driver: overlay

services:
  knotx:
    image: knotx/knotx-performance-target
    ports:
      - "8092:8092"
      - "9010:9010"
#    extra_hosts:
#      - "host.docker.internal:your-host-ip"
    networks:
      - private

  jmxtrans:
    image: jmxtrans/jmxtrans
    volumes:
      - ./jmxtrans:/var/lib/jmxtrans
    networks:
      - private

  cadvisor:
    image: google/cadvisor
    command: -storage_driver=influxdb -storage_driver_db=monitoring -storage_driver_host=host.docker.internal:8086
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
#    extra_hosts:
#      - "host.docker.internal:your-host-ip"
    networks:
      - private